services:
  thar:
    build: .
    container_name: bot
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
    restart: always
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
